# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
blank_lines: false
bullet: false
html: false
indentation: false
line_length: false
spaces: false
url: false
whitespace: false

# Allow e.g. Changelog.md to have the same headings under each release
no-duplicate-heading:
  siblings_only: true
