# Docs: https://rust-lang.github.io/rustfmt/
edition = "2024"
use_field_init_shorthand = true

# unstable rustfmt options
imports_granularity = "crate"
group_imports = "StdExternalCrate"
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
