[package]
name = "tooters"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console-subscriber = "0.1"
crossterm = { version = "0.26", features = ["event-stream"] }
futures = "0.3"
mastodon-async = { version = "1.2", features = ["toml"] }
ratatui = { git = "https://github.com/tui-rs-revival/ratatui.git" }
#tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time", "tracing"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
indoc = "2"
