[package]
name = "tooters"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.26", features = ["event-stream"] }
futures = "0.3"
ratatui = { git = "https://github.com/tui-rs-revival/ratatui.git" }
tokio = { version = "1", features = ["full"] }
