[package]
name = "toot-rs"
version = "0.0.6"
edition = "2021"
license-file = "LICENSE.txt"
description = "Renamed to Tooters. See https://crates.io/crates/tooters"
homepage = "https://toot.rs"
repository = "https://github.com/joshka/tooters"
readme = "README.md"
keywords = ["mastodon", "tui", "cli"]
categories = ["command-line-utilities"]


[dependencies]
indoc = "2"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.5"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.67.1"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "aarch64-apple-darwin",
]
