[package]
name = "tooters"
version = "0.0.1"
edition = "2021"
license-file = "LICENSE.txt"
description = "A Rust TUI-based Mastodon App"
homepage = "https://toote.rs"
repository = "https://github.com/joshka/tooters"
readme = "README.md"
keywords = ["mastodon", "tui", "cli"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = { version = "0.26", features = ["event-stream"] }
futures = "0.3"
html2text = "0.5"
mastodon-async = { version = "1.2", features = ["toml"] }
ratatui = { version = "0.20" }
time = "0.3"
tokio = { version = "1", features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tracing",
] }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
indoc = "2"
